### ISSUE TITLE
Environment variables not expanded.

### ISSUE THREAD

**Issue by chainhead** [alpine-docker/k8s#41]
I am passing environment variables via `ConfigMap` into my `Deployment` that uses `alpine/k8s:1.26.0`

```yaml
        - name: scan-rbac
          image: alpine/k8s:1.26.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - "-c"
            - >-
              env &&
              echo "Scanning objects for cluster ${CLUSTER_NAME}" &&
```

The `env` does list `CLUSTER_NAME` correctly as set in `ConfigMap`. However, `Scanning objects for cluster ${CLUSTER_NAME}` does not expand `CLUSTER_NAME`. What am I missing?
